### ISSUE TITLE
Missing gamerule info in mod description

### ISSUE THREAD

**Issue by JohnZ03** [ReviversMC/bettersleeping#2]
To change percentage of players required to sleep, the gamerule to be changed is "/gamerule PLAYERS_SLEEPING_PERCENTAGE". This is missing on the mod website (https://modrinth.com/mod/bettersleeping-revived). Please add the info if possible.

**Comment by wereii** [comment]
I expected this to be in the config but was confused that I can't find it anywhere. 
Edit: ~~My latest Fabric server does not seem to have /gamerule command (not even from RCON)~~ :facepalm:

**Comment by NebelNidas** [comment]
Sorry for the late reply, it seems I unfollowed my own project somehow and therefore haven't received a notification from GitHub. 😬 Regarding the description: I have updated the one on CurseForge, but forgot the one on Modrinth! I'll fix it asap.
