### ISSUE TITLE
Can be marked as 1.20.1 compatible

### ISSUE THREAD

**Issue by sternschnaube** [ReviversMC/bettersleeping#26]
Please update the version listing on Modrinth 😊

**Comment by thefirethirteen** [comment]
It already is. :)

**Comment by venaminecraft** [comment]
I don't see it here:
https://modrinth.com/mod/bettersleeping-revived/versions

**Comment by thefirethirteen** [comment]
Oh, sorry, I thought this was the bug tracker for modern glass doors :)

**Comment by NebelNidas** [comment]
I just tested it, and it seems to crash when trying to apply debuffs. I'll try to see what's going on

**Comment by venaminecraft** [comment]
Any update on this @NebelNidas? 😊

**Comment by venaminecraft** [comment]
Again, any update on this @NebelNidas?

**Comment by NebelNidas** [comment]
Sorry for the delay, this build here should work: https://github.com/ReviversMC/bettersleeping/actions/runs/9235784377

Can you verify?

**Comment by venaminecraft** [comment]
It's still for 1.20.1 and not 1.20.6, right?

**Comment by NebelNidas** [comment]
Currently only up to 1.20.4, as 1.20.5 introduced some changes around the status effect system I have to investigate first

**Comment by venaminecraft** [comment]
I can check the mod later for 1.20.4. Thanks for the update and I hope for 1.20.6 😄

**Comment by NebelNidas** [comment]
Closing this now. Should you notice any problems, please open a new issue 👍
